# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='startingTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
